// PLACEHOLDER CONFIGURATION -- SEE SETUP.md
//
// This file is normally generated by the FlutterFire CLI:
//
//     dart pub global activate flutterfire_cli
//     flutterfire configure
//
// That command must be run while signed in to the Google account that owns the
// Firebase project, so it could not be run on this machine. Every value marked
// TODO_REPLACE_ME below must be filled in before the app can reach Firebase.
//
// Values come from the Firebase console:
//   Project settings -> General -> Your apps -> SDK setup and configuration
//
// None of these values are secrets. A Firebase "apiKey" identifies the project;
// it does not grant access on its own. Access is controlled by Firebase
// Authentication plus the rules in firestore.rules.

import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions, FirebaseException;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Sentinel used for every value that still needs to be filled in.
const String kFirebasePlaceholder = 'TODO_REPLACE_ME';

class DefaultFirebaseOptions {
  const DefaultFirebaseOptions._();

  /// True once every placeholder in the active platform's options is replaced.
  ///
  /// [FirebaseBootstrap] checks this before calling `Firebase.initializeApp`, so
  /// an unconfigured build shows a readable setup screen instead of a crash.
  static bool get isConfigured {
    final FirebaseOptions options = currentPlatform;
    return <String?>[
      options.apiKey,
      options.appId,
      options.projectId,
      options.messagingSenderId,
    ].every(
      (String? value) => value != null && !value.contains(kFirebasePlaceholder),
    );
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for $defaultTargetPlatform. '
          'Re-run `flutterfire configure` and include that platform.',
        );
    }
  }

  // --- Web -----------------------------------------------------------------
  // Console -> Project settings -> Your apps -> Web app -> Config

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtgBrwHWNE7LYi3YM2usOjOsBYOtsfbig',
    appId: '1:978597685925:web:d1ad1bf1634bceacdffb4c',
    messagingSenderId: '978597685925',
    projectId: 'ocean-list',
    authDomain: 'ocean-list.firebaseapp.com',
    storageBucket: 'ocean-list.firebasestorage.app',
  );
  // --- macOS ---------------------------------------------------------------
  // Console -> Project settings -> Your apps -> Apple app (macOS bundle id)

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPbA09gHkomsOIr3bDs0FE1Bhlk-UfMQ8',
    appId: '1:978597685925:ios:f7b879190b44fca2dffb4c',
    messagingSenderId: '978597685925',
    projectId: 'ocean-list',
    storageBucket: 'ocean-list.firebasestorage.app',
    iosBundleId: 'com.example.ultraPlanner',
  );
  // --- iOS -----------------------------------------------------------------
  // Console -> Project settings -> Your apps -> Apple app (iOS bundle id)

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPbA09gHkomsOIr3bDs0FE1Bhlk-UfMQ8',
    appId: '1:978597685925:ios:f7b879190b44fca2dffb4c',
    messagingSenderId: '978597685925',
    projectId: 'ocean-list',
    storageBucket: 'ocean-list.firebasestorage.app',
    iosBundleId: 'com.example.ultraPlanner',
  );
  // --- Android -------------------------------------------------------------
  // Only needed if an android/ folder is added to this project.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: kFirebasePlaceholder,
    appId: kFirebasePlaceholder,
    messagingSenderId: kFirebasePlaceholder,
    projectId: kFirebasePlaceholder,
    storageBucket: '$kFirebasePlaceholder.firebasestorage.app',
  );
}

/// Human-readable explanation for a failed `Firebase.initializeApp`.
String describeFirebaseStartupError(Object error) {
  if (error is FirebaseException) {
    return error.message ?? error.code;
  }
  return error.toString();
}
